/**
 * CSV helpers. User-entered text can start with = + - @ (or a tab/CR), which spreadsheet
 * apps run as a formula ("CSV injection"). Such cells are prefixed with an apostrophe.
 */
const FORMULA_START = /^[=+\-@\t\r]/;

export function csvText(value: string): string {
  const safe = FORMULA_START.test(value) ? `'${value}` : value;
  return `"${safe.replace(/"/g, '""')}"`;
}

/** Numbers are written as-is: they are generated by the app, not typed as free text. */
export function csvNumber(value: number): string {
  return Number.isFinite(value) ? String(value) : "";
}

export interface CsvTransaction {
  date: string;
  type: string;
  category: string;
  amount: number;
  note: string;
}

/** UTF-8 with BOM so Excel shows Thai correctly. Newest first. */
export function transactionsToCsv(rows: CsvTransaction[]): string {
  const sorted = [...rows].sort((a, b) => (a.date < b.date ? 1 : -1));
  const lines = ["date,type,category,amount,note"].concat(
    sorted.map((t) => [csvText(t.date), csvText(t.type), csvText(t.category), csvNumber(t.amount), csvText(t.note)].join(","))
  );
  return "﻿" + lines.join("\r\n");
}
